From root@cyka.ru Tue May 22 13:05:19 2007
Return-path: <root@cyka.ru>
Envelope-to: sms@cyka.ru
Delivery-date: Tue, 22 May 2007 13:05:19 +0400
Received: from root by cyka.ru with local (Exim 4.66)
        id 1HqQIx-000EZX-3Y
        for sms@cyka.ru; Tue, 22 May 2007 13:05:19 +0400
To: sms@cyka.ru
Subject: 79037646969
Message-Id: <E1HqQIx-000EZX-3Y@cyka.ru>
From: Root <root@cyka.ru>
Date: Tue, 22 May 2007 13:05:19 +0400
X-SA-Exim-Scanned: No (on cyka.ru); SAEximRunCond expanded to false

test sms sending
